import type { Plant, PlantCommunity } from "@/types/plant";

// Note: This is a curated starter dataset for Marin County natives.
// Occurrence points are optional; when present they enable 2km filtering.

export const PLANTS: Plant[] = [
  {
    scientificName: "Quercus agrifolia",
    commonName: "Coast Live Oak",
    communities: ["Oak Woodland", "Chaparral"],
    wildlifeSupportScore: 400,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 200,
    matureHeightFt: 60,
    matureWidthFt: 70,
    growthRate: "Moderate",
    flowerColors: ["yellow-green"],
    bloomMonths: [3, 4],
    indigenousUses: ["acorns leached for meal", "wood for tools and fuel"],
    butterflies: [
      { commonName: "California Sister", scientificName: "Adelpha californica" },
      { commonName: "Propertius Duskywing", scientificName: "Erynnis propertius" },
      { commonName: "Mournful Duskywing", scientificName: "Erynnis tristis" },
    ],
    birds: [
      { commonName: "Acorn Woodpecker", scientificName: "Melanerpes formicivorus" },
      { commonName: "Oak Titmouse", scientificName: "Baeolophus inornatus" },
      { commonName: "Western Scrub-Jay", scientificName: "Aphelocoma californica" },
    ],
  },
  {
    scientificName: "Quercus lobata",
    commonName: "Valley Oak",
    communities: ["Oak Woodland", "Grassland"],
    wildlifeSupportScore: 350,
    evergreenDeciduous: "Deciduous",
    lifespanYears: 250,
    matureHeightFt: 70,
    matureWidthFt: 80,
    growthRate: "Moderate",
    flowerColors: ["yellow-green"],
    bloomMonths: [4, 5],
    indigenousUses: ["acorns for food", "bark used traditionally"],
    butterflies: [
      { commonName: "California Sister" },
      { commonName: "Lorquin's Admiral", scientificName: "Limenitis lorquini" },
      { commonName: "Mournful Duskywing" },
    ],
    birds: [
      { commonName: "Acorn Woodpecker" },
      { commonName: "American Robin" },
      { commonName: "Northern Flicker" },
    ],
  },
  {
    scientificName: "Ceanothus thyrsiflorus",
    commonName: "Blueblossom",
    communities: ["Chaparral", "Oak Woodland"],
    wildlifeSupportScore: 180,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 25,
    matureHeightFt: 15,
    matureWidthFt: 12,
    growthRate: "Fast",
    flowerColors: ["blue"],
    bloomMonths: [3, 4, 5],
    indigenousUses: ["flowers used as gentle soap"],
    butterflies: [
      { commonName: "Ceanothus Silk Moth", scientificName: "Hyalophora euryalus" },
      { commonName: "Mournful Duskywing" },
    ],
    birds: [
      { commonName: "Wrentit" },
      { commonName: "Anna's Hummingbird" },
    ],
  },
  {
    scientificName: "Arctostaphylos manzanita",
    commonName: "Common Manzanita",
    communities: ["Chaparral"],
    wildlifeSupportScore: 160,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 50,
    matureHeightFt: 12,
    matureWidthFt: 10,
    growthRate: "Moderate",
    flowerColors: ["white", "pink"],
    bloomMonths: [1, 2, 3],
    indigenousUses: ["berries eaten fresh or dried", "wood for tools"],
    butterflies: [
      { commonName: "Brown Elfin", scientificName: "Callophrys augustinus" },
      { commonName: "California Hairstreak", scientificName: "Satyrium californica" },
    ],
    birds: [
      { commonName: "Wrentit" },
      { commonName: "California Thrasher" },
    ],
  },
  {
    scientificName: "Heteromeles arbutifolia",
    commonName: "Toyon",
    communities: ["Chaparral", "Oak Woodland"],
    wildlifeSupportScore: 160,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 90,
    matureHeightFt: 15,
    matureWidthFt: 12,
    growthRate: "Moderate",
    flowerColors: ["white"],
    bloomMonths: [5, 6],
    indigenousUses: ["berries eaten cooked", "wood for tools"],
    butterflies: [
      { commonName: "Gray Hairstreak", scientificName: "Strymon melinus" },
      { commonName: "California Hairstreak" },
    ],
    birds: [
      { commonName: "Cedar Waxwing" },
      { commonName: "American Robin" },
    ],
  },
  {
    scientificName: "Artemisia californica",
    commonName: "California Sagebrush",
    communities: ["Chaparral", "Grassland"],
    wildlifeSupportScore: 150,
    evergreenDeciduous: "Semi-evergreen",
    lifespanYears: 30,
    matureHeightFt: 5,
    matureWidthFt: 6,
    growthRate: "Fast",
    flowerColors: ["yellow"],
    bloomMonths: [8, 9],
    indigenousUses: ["aromatic leaves for medicine"],
    butterflies: [
      { commonName: "Western Tiger Swallowtail", scientificName: "Papilio rutulus" },
    ],
    birds: [
      { commonName: "Hermit Thrush" },
      { commonName: "Swainson's Thrush" },
    ],
  },
  {
    scientificName: "Eriogonum nudum",
    commonName: "Naked Buckwheat",
    communities: ["Chaparral"],
    wildlifeSupportScore: 130,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 30,
    matureHeightFt: 3,
    matureWidthFt: 4,
    growthRate: "Fast",
    flowerColors: ["white", "pink"],
    bloomMonths: [5, 6, 7, 8, 9],
    indigenousUses: ["seeds ground for food"],
    butterflies: [
      { commonName: "Acmon Blue", scientificName: "Plebejus acmon" },
      { commonName: "Dotted Blue", scientificName: "Euphilotes spp." },
    ],
  },
  {
    scientificName: "Ribes sanguineum var. glutinosum",
    commonName: "Pink Flowering Currant",
    communities: ["Oak Woodland", "Riparian"],
    wildlifeSupportScore: 120,
    evergreenDeciduous: "Deciduous",
    lifespanYears: 20,
    matureHeightFt: 10,
    matureWidthFt: 8,
    growthRate: "Moderate",
    flowerColors: ["pink"],
    bloomMonths: [2, 3, 4],
    indigenousUses: ["berries eaten fresh", "stems for tools"],
    butterflies: [
      { commonName: "Sphinx Moths", scientificName: "Sphingidae (various)" },
    ],
  },
  {
    scientificName: "Baccharis pilularis",
    commonName: "Coyote Brush",
    communities: ["Chaparral", "Grassland", "Oak Woodland", "Riparian"],
    wildlifeSupportScore: 100,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 25,
    matureHeightFt: 8,
    matureWidthFt: 10,
    growthRate: "Fast",
    flowerColors: ["white"],
    bloomMonths: [8, 9, 10],
    indigenousUses: ["windbreak, erosion control"],
    butterflies: [
      { commonName: "California Hairstreak" },
      { commonName: "Fiery Skipper", scientificName: "Hylephila phyleus" },
    ],
  },
  {
    scientificName: "Frangula californica",
    commonName: "Coffeeberry",
    communities: ["Oak Woodland", "Chaparral"],
    wildlifeSupportScore: 120,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 50,
    matureHeightFt: 8,
    matureWidthFt: 8,
    growthRate: "Moderate",
    flowerColors: ["greenish"],
    bloomMonths: [4, 5, 6],
    indigenousUses: ["berries used as dye"],
    butterflies: [
      { commonName: "Pale Swallowtail", scientificName: "Papilio eurymedon" },
    ],
  },
  {
    scientificName: "Umbellularia californica",
    commonName: "California Bay Laurel",
    communities: ["Oak Woodland", "Riparian"],
    wildlifeSupportScore: 110,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 100,
    matureHeightFt: 40,
    matureWidthFt: 25,
    growthRate: "Moderate",
    flowerColors: ["yellow-green"],
    bloomMonths: [2, 3, 4],
    indigenousUses: ["leaves for seasoning and medicine"],
    butterflies: [
      { commonName: "Western Tiger Swallowtail" },
    ],
  },
  {
    scientificName: "Sambucus nigra ssp. caerulea",
    commonName: "Blue Elderberry",
    communities: ["Riparian", "Oak Woodland"],
    wildlifeSupportScore: 120,
    evergreenDeciduous: "Deciduous",
    lifespanYears: 60,
    matureHeightFt: 20,
    matureWidthFt: 20,
    growthRate: "Fast",
    flowerColors: ["white"],
    bloomMonths: [4, 5, 6],
    indigenousUses: ["berries for food and dye", "wood for flutes"],
    butterflies: [
      { commonName: "Lorquin's Admiral" },
      { commonName: "Mourning Cloak", scientificName: "Nymphalis antiopa" },
    ],
  },
  {
    scientificName: "Juncus patens",
    commonName: "California Gray Rush",
    communities: ["Riparian"],
    wildlifeSupportScore: 60,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 20,
    matureHeightFt: 3,
    matureWidthFt: 3,
    growthRate: "Fast",
    flowerColors: ["brown"],
    bloomMonths: [5, 6, 7],
    indigenousUses: ["basketry"],
    butterflies: [],
  },
  {
    scientificName: "Nassella pulchra",
    commonName: "Purple Needlegrass",
    communities: ["Grassland", "Chaparral"],
    wildlifeSupportScore: 70,
    evergreenDeciduous: "Semi-evergreen",
    lifespanYears: 150,
    matureHeightFt: 3,
    matureWidthFt: 2,
    growthRate: "Moderate",
    flowerColors: ["purple"],
    bloomMonths: [4, 5],
    indigenousUses: ["seed heads for adornment"],
    butterflies: [
      { commonName: "Common Checkered-Skipper", scientificName: "Burnsius communis" },
    ],
  },
  {
    scientificName: "Diplacus aurantiacus",
    commonName: "Sticky Monkeyflower",
    communities: ["Chaparral", "Oak Woodland"],
    wildlifeSupportScore: 100,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 20,
    matureHeightFt: 4,
    matureWidthFt: 4,
    growthRate: "Moderate",
    flowerColors: ["orange"],
    bloomMonths: [4, 5, 6, 7],
    indigenousUses: ["leaves for poultice"],
    butterflies: [
      { commonName: "Variable Checkerspot", scientificName: "Euphydryas chalcedona" },
    ],
  },
  {
    scientificName: "Achillea millefolium",
    commonName: "Yarrow",
    communities: ["Grassland", "Oak Woodland", "Riparian"],
    wildlifeSupportScore: 80,
    evergreenDeciduous: "Semi-evergreen",
    lifespanYears: 15,
    matureHeightFt: 2,
    matureWidthFt: 2,
    growthRate: "Fast",
    flowerColors: ["white"],
    bloomMonths: [5, 6, 7, 8, 9],
    indigenousUses: ["medicinal tea and poultice"],
    butterflies: [
      { commonName: "Painted Lady", scientificName: "Vanessa cardui" },
    ],
  },
  {
    scientificName: "Symphyotrichum chilense",
    commonName: "California Aster",
    communities: ["Grassland", "Riparian"],
    wildlifeSupportScore: 85,
    evergreenDeciduous: "Deciduous",
    lifespanYears: 10,
    matureHeightFt: 3,
    matureWidthFt: 3,
    growthRate: "Fast",
    flowerColors: ["purple", "lavender"],
    bloomMonths: [7, 8, 9, 10],
    indigenousUses: ["nectar source", "pollinator support"],
    butterflies: [
      { commonName: "West Coast Lady", scientificName: "Vanessa annabella" },
    ],
  },
  {
    scientificName: "Lupinus nanus",
    commonName: "Sky Lupine",
    communities: ["Chaparral", "Grassland", "Oak Woodland"],
    wildlifeSupportScore: 120,
    evergreenDeciduous: "Deciduous",
    lifespanYears: 3,
    matureHeightFt: 2,
    matureWidthFt: 2,
    growthRate: "Fast",
    flowerColors: ["blue", "purple"],
    bloomMonths: [3, 4, 5],
    indigenousUses: ["seeds ground for food"],
    butterflies: [
      { commonName: "Acmon Blue", scientificName: "Plebejus acmon" },
      { commonName: "Silvery Blue", scientificName: "Glaucopsyche lygdamus" },
    ],
    birds: [
      { commonName: "Anna's Hummingbird" },
      { commonName: "Allen's Hummingbird" },
    ],
  },
  {
    scientificName: "Eschscholzia californica",
    commonName: "California Poppy",
    communities: ["Chaparral", "Grassland"],
    wildlifeSupportScore: 90,
    evergreenDeciduous: "Deciduous",
    lifespanYears: 2,
    matureHeightFt: 1,
    matureWidthFt: 1,
    growthRate: "Fast",
    flowerColors: ["orange", "yellow"],
    bloomMonths: [2, 3, 4, 5, 6],
    indigenousUses: ["flowers used medicinally"],
    butterflies: [
      { commonName: "Checkered White", scientificName: "Pontia protodice" },
    ],
    birds: [
      { commonName: "Anna's Hummingbird" },
    ],
  },
  {
    scientificName: "Epilobium canum",
    commonName: "California Fuchsia",
    communities: ["Chaparral", "Oak Woodland"],
    wildlifeSupportScore: 110,
    evergreenDeciduous: "Semi-evergreen",
    lifespanYears: 5,
    matureHeightFt: 2,
    matureWidthFt: 3,
    growthRate: "Fast",
    flowerColors: ["red", "orange"],
    bloomMonths: [7, 8, 9, 10],
    indigenousUses: ["flowers used medicinally"],
    butterflies: [
      { commonName: "Checkered White", scientificName: "Pontia protodice" },
    ],
    birds: [
      { commonName: "Anna's Hummingbird" },
      { commonName: "Allen's Hummingbird" },
    ],
  },
  {
    scientificName: "Corylus cornuta",
    commonName: "Beaked Hazelnut",
    communities: ["Oak Woodland", "Riparian"],
    wildlifeSupportScore: 100,
    evergreenDeciduous: "Deciduous",
    lifespanYears: 50,
    matureHeightFt: 15,
    matureWidthFt: 12,
    growthRate: "Moderate",
    flowerColors: ["yellow"],
    bloomMonths: [2, 3],
    indigenousUses: ["nuts eaten fresh or roasted"],
    butterflies: [
      { commonName: "Mourning Cloak", scientificName: "Nymphalis antiopa" },
    ],
    birds: [
      { commonName: "Steller's Jay" },
      { commonName: "Scrub Jay" },
    ],
  },
  {
    scientificName: "Vaccinium ovatum",
    commonName: "Evergreen Huckleberry",
    communities: ["Oak Woodland", "Riparian"],
    wildlifeSupportScore: 80,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 30,
    matureHeightFt: 8,
    matureWidthFt: 6,
    growthRate: "Slow",
    flowerColors: ["white", "pink"],
    bloomMonths: [4, 5],
    indigenousUses: ["berries eaten fresh or dried"],
    butterflies: [
      { commonName: "Brown Elfin", scientificName: "Callophrys augustinus" },
    ],
    birds: [
      { commonName: "Hermit Thrush" },
      { commonName: "Swainson's Thrush" },
    ],
  },
  {
    scientificName: "Arbutus menziesii",
    commonName: "Pacific Madrone",
    communities: ["Oak Woodland", "Chaparral"],
    wildlifeSupportScore: 150,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 200,
    matureHeightFt: 50,
    matureWidthFt: 30,
    growthRate: "Slow",
    flowerColors: ["white"],
    bloomMonths: [4, 5],
    indigenousUses: ["berries eaten fresh", "wood for tools"],
    butterflies: [
      { commonName: "California Sister", scientificName: "Adelpha californica" },
    ],
    birds: [
      { commonName: "American Robin" },
      { commonName: "Cedar Waxwing" },
    ],
  },
  {
    scientificName: "Clinopodium douglasii",
    commonName: "Yerba Buena",
    communities: ["Oak Woodland", "Chaparral", "Riparian"],
    wildlifeSupportScore: 70,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 5,
    matureHeightFt: 1,
    matureWidthFt: 3,
    growthRate: "Fast",
    flowerColors: ["white"],
    bloomMonths: [4, 5, 6],
    indigenousUses: ["leaves used for tea"],
    butterflies: [
      { commonName: "Checkered White", scientificName: "Pontia protodice" },
    ],
    birds: [
      { commonName: "Anna's Hummingbird" },
    ],
  },
  {
    scientificName: "Fragaria vesca",
    commonName: "Woodland Strawberry",
    communities: ["Oak Woodland", "Riparian"],
    wildlifeSupportScore: 60,
    evergreenDeciduous: "Deciduous",
    lifespanYears: 3,
    matureHeightFt: 0.5,
    matureWidthFt: 2,
    growthRate: "Fast",
    flowerColors: ["white"],
    bloomMonths: [4, 5, 6],
    indigenousUses: ["berries eaten fresh"],
    butterflies: [
      { commonName: "Checkered White", scientificName: "Pontia protodice" },
    ],
    birds: [
      { commonName: "American Robin" },
      { commonName: "Hermit Thrush" },
    ],
  },
  {
    scientificName: "Festuca californica",
    commonName: "California Fescue",
    communities: ["Chaparral", "Oak Woodland"],
    wildlifeSupportScore: 50,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 10,
    matureHeightFt: 3,
    matureWidthFt: 2,
    growthRate: "Moderate",
    flowerColors: ["green"],
    bloomMonths: [5, 6],
    indigenousUses: ["seeds ground for food"],
    butterflies: [
      { commonName: "Common Ringlet", scientificName: "Coenonympha tullia" },
    ],
    birds: [
      { commonName: "Dark-eyed Junco" },
      { commonName: "White-crowned Sparrow" },
    ],
  },
  {
    scientificName: "Melica californica",
    commonName: "California Melic",
    communities: ["Grassland", "Oak Woodland", "Riparian"],
    wildlifeSupportScore: 45,
    evergreenDeciduous: "Semi-evergreen",
    lifespanYears: 8,
    matureHeightFt: 2,
    matureWidthFt: 1,
    growthRate: "Moderate",
    flowerColors: ["green"],
    bloomMonths: [4, 5],
    indigenousUses: ["seeds ground for food"],
    butterflies: [
      { commonName: "Common Ringlet", scientificName: "Coenonympha tullia" },
    ],
    birds: [
      { commonName: "Dark-eyed Junco" },
      { commonName: "White-crowned Sparrow" },
    ],
  },
  {
    scientificName: "Carex obnupta",
    commonName: "Slough Sedge",
    communities: ["Riparian"],
    wildlifeSupportScore: 40,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 15,
    matureHeightFt: 2,
    matureWidthFt: 2,
    growthRate: "Fast",
    flowerColors: ["green"],
    bloomMonths: [4, 5],
    indigenousUses: ["leaves used for weaving"],
    butterflies: [
      { commonName: "Common Ringlet", scientificName: "Coenonympha tullia" },
    ],
    birds: [
      { commonName: "Dark-eyed Junco" },
      { commonName: "White-crowned Sparrow" },
    ],
  },
  {
    scientificName: "Elymus glaucus",
    commonName: "Blue Wildrye",
    communities: ["Grassland", "Oak Woodland", "Riparian"],
    wildlifeSupportScore: 55,
    evergreenDeciduous: "Semi-evergreen",
    lifespanYears: 5,
    matureHeightFt: 4,
    matureWidthFt: 2,
    growthRate: "Fast",
    flowerColors: ["green"],
    bloomMonths: [5, 6],
    indigenousUses: ["seeds ground for food"],
    butterflies: [
      { commonName: "Common Ringlet", scientificName: "Coenonympha tullia" },
    ],
    birds: [
      { commonName: "Dark-eyed Junco" },
      { commonName: "White-crowned Sparrow" },
    ],
  },
  {
    scientificName: "Bromus carinatus",
    commonName: "California Brome",
    communities: ["Grassland", "Chaparral"],
    wildlifeSupportScore: 50,
    evergreenDeciduous: "Semi-evergreen",
    lifespanYears: 3,
    matureHeightFt: 3,
    matureWidthFt: 1,
    growthRate: "Fast",
    flowerColors: ["green"],
    bloomMonths: [4, 5, 6],
    indigenousUses: ["seeds ground for food"],
    butterflies: [
      { commonName: "Common Ringlet", scientificName: "Coenonympha tullia" },
    ],
    birds: [
      { commonName: "Dark-eyed Junco" },
      { commonName: "White-crowned Sparrow" },
    ],
  },
  {
    scientificName: "Deschampsia cespitosa",
    commonName: "Tufted Hairgrass",
    communities: ["Riparian", "Oak Woodland"],
    wildlifeSupportScore: 45,
    evergreenDeciduous: "Semi-evergreen",
    lifespanYears: 8,
    matureHeightFt: 2,
    matureWidthFt: 2,
    growthRate: "Moderate",
    flowerColors: ["green"],
    bloomMonths: [5, 6],
    indigenousUses: ["seeds ground for food"],
    butterflies: [
      { commonName: "Common Ringlet", scientificName: "Coenonympha tullia" },
    ],
    birds: [
      { commonName: "Dark-eyed Junco" },
      { commonName: "White-crowned Sparrow" },
    ],
  },
  {
    scientificName: "Koeleria macrantha",
    commonName: "Prairie Junegrass",
    communities: ["Grassland", "Chaparral"],
    wildlifeSupportScore: 40,
    evergreenDeciduous: "Semi-evergreen",
    lifespanYears: 5,
    matureHeightFt: 2,
    matureWidthFt: 1,
    growthRate: "Moderate",
    flowerColors: ["green"],
    bloomMonths: [5, 6],
    indigenousUses: ["seeds ground for food"],
    butterflies: [
      { commonName: "Common Ringlet", scientificName: "Coenonympha tullia" },
    ],
    birds: [
      { commonName: "Dark-eyed Junco" },
      { commonName: "White-crowned Sparrow" },
    ],
  },
  // California Pipevine - critical host plant for Pipevine Swallowtail
  {
    scientificName: "Aristolochia californica",
    commonName: "California Pipevine",
    communities: ["Oak Woodland", "Riparian"],
    wildlifeSupportScore: 200,
    evergreenDeciduous: "Deciduous",
    lifespanYears: 30,
    matureHeightFt: 20,
    matureWidthFt: 15,
    growthRate: "Fast",
    flowerColors: ["brown", "purple"],
    bloomMonths: [2, 3, 4],
    indigenousUses: ["medicinal uses", "basketry"],
    butterflies: [
      { commonName: "Pipevine Swallowtail", scientificName: "Battus philenor" },
      { commonName: "California Pipevine Swallowtail", scientificName: "Battus philenor hirsuta" },
    ],
    birds: [
      { commonName: "Anna's Hummingbird" },
      { commonName: "Allen's Hummingbird" },
    ],
  },
  // Narrow-leaf Milkweed - critical host plant for Monarch butterflies
  {
    scientificName: "Asclepias fascicularis",
    commonName: "Narrow-leaf Milkweed",
    communities: ["Grassland", "Oak Woodland", "Riparian"],
    wildlifeSupportScore: 180,
    evergreenDeciduous: "Deciduous",
    lifespanYears: 5,
    matureHeightFt: 3,
    matureWidthFt: 2,
    growthRate: "Moderate",
    flowerColors: ["white", "pink"],
    bloomMonths: [6, 7, 8, 9],
    indigenousUses: ["medicinal uses", "fiber for cordage"],
    butterflies: [
      { commonName: "Monarch", scientificName: "Danaus plexippus" },
      { commonName: "Queen", scientificName: "Danaus gilippus" },
    ],
    birds: [
      { commonName: "Anna's Hummingbird" },
      { commonName: "Allen's Hummingbird" },
    ],
  },
  // Douglas Iris - beautiful spring wildflower
  {
    scientificName: "Iris douglasiana",
    commonName: "Douglas Iris",
    communities: ["Oak Woodland", "Chaparral", "Grassland"],
    wildlifeSupportScore: 80,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 15,
    matureHeightFt: 2,
    matureWidthFt: 2,
    growthRate: "Moderate",
    flowerColors: ["purple", "blue", "white"],
    bloomMonths: [3, 4, 5],
    indigenousUses: ["fiber for cordage", "medicinal uses"],
    butterflies: [
      { commonName: "Mourning Cloak", scientificName: "Nymphalis antiopa" },
    ],
    birds: [
      { commonName: "Anna's Hummingbird" },
      { commonName: "Allen's Hummingbird" },
    ],
  },
  // Soap Plant - important traditional plant
  {
    scientificName: "Chlorogalum pomeridianum",
    commonName: "Soap Plant",
    communities: ["Oak Woodland", "Grassland"],
    wildlifeSupportScore: 60,
    evergreenDeciduous: "Deciduous",
    lifespanYears: 10,
    matureHeightFt: 3,
    matureWidthFt: 1,
    growthRate: "Moderate",
    flowerColors: ["white"],
    bloomMonths: [5, 6, 7],
    indigenousUses: ["bulb used as soap", "fiber for brushes"],
    butterflies: [
      { commonName: "Checkered White", scientificName: "Pontia protodice" },
    ],
    birds: [
      { commonName: "Anna's Hummingbird" },
    ],
  },
  // Western Sword Fern - classic woodland fern
  {
    scientificName: "Polystichum munitum",
    commonName: "Western Sword Fern",
    communities: ["Oak Woodland", "Riparian"],
    wildlifeSupportScore: 40,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 50,
    matureHeightFt: 4,
    matureWidthFt: 3,
    growthRate: "Slow",
    flowerColors: ["none"],
    bloomMonths: [],
    indigenousUses: ["fronds for basketry", "medicinal uses"],
    butterflies: [],
    birds: [
      { commonName: "Dark-eyed Junco" },
      { commonName: "White-crowned Sparrow" },
    ],
  },
  // Woodland Strawberry - important groundcover
  {
    scientificName: "Fragaria vesca",
    commonName: "Woodland Strawberry",
    communities: ["Oak Woodland", "Riparian"],
    wildlifeSupportScore: 80,
    evergreenDeciduous: "Semi-evergreen",
    lifespanYears: 5,
    matureHeightFt: 0.5,
    matureWidthFt: 2,
    growthRate: "Fast",
    flowerColors: ["white"],
    bloomMonths: [3, 4, 5],
    indigenousUses: ["berries for food", "medicinal uses"],
    butterflies: [
      { commonName: "Checkered White", scientificName: "Pontia protodice" },
    ],
    birds: [
      { commonName: "American Robin" },
      { commonName: "Cedar Waxwing" },
    ],
  },
  // California Brome - native grass for grasslands
  {
    scientificName: "Bromus carinatus",
    commonName: "California Brome",
    communities: ["Grassland", "Oak Woodland", "Chaparral"],
    wildlifeSupportScore: 50,
    evergreenDeciduous: "Semi-evergreen",
    lifespanYears: 3,
    matureHeightFt: 3,
    matureWidthFt: 1,
    growthRate: "Fast",
    flowerColors: ["green"],
    bloomMonths: [4, 5, 6],
    indigenousUses: ["seeds ground for food"],
    butterflies: [
      { commonName: "Common Ringlet", scientificName: "Coenonympha tullia" },
    ],
    birds: [
      { commonName: "Dark-eyed Junco" },
      { commonName: "White-crowned Sparrow" },
    ],
  },
  // Coastal Scrub plants
  {
    scientificName: "Artemisia californica",
    commonName: "California Sagebrush",
    communities: ["Coastal Scrub", "Chaparral"],
    wildlifeSupportScore: 150,
    evergreenDeciduous: "Semi-evergreen",
    lifespanYears: 15,
    matureHeightFt: 5,
    matureWidthFt: 6,
    growthRate: "Moderate",
    flowerColors: ["yellow-green"],
    bloomMonths: [8, 9, 10],
    indigenousUses: ["medicinal uses", "smudging"],
    butterflies: [
      { commonName: "California Sister", scientificName: "Adelpha californica" },
      { commonName: "Mournful Duskywing", scientificName: "Erynnis tristis" },
    ],
    birds: [
      { commonName: "Wrentit" },
      { commonName: "California Thrasher" },
    ],
  },
  {
    scientificName: "Baccharis pilularis",
    commonName: "Coyote Brush",
    communities: ["Coastal Scrub", "Chaparral", "Oak Woodland"],
    wildlifeSupportScore: 100,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 20,
    matureHeightFt: 8,
    matureWidthFt: 10,
    growthRate: "Fast",
    flowerColors: ["white"],
    bloomMonths: [9, 10, 11],
    indigenousUses: ["basketry", "medicinal uses"],
    butterflies: [
      { commonName: "Checkered White", scientificName: "Pontia protodice" },
      { commonName: "Common Ringlet", scientificName: "Coenonympha tullia" },
    ],
    birds: [
      { commonName: "Wrentit" },
      { commonName: "California Thrasher" },
    ],
  },
  {
    scientificName: "Eriogonum latifolium",
    commonName: "Coastal Buckwheat",
    communities: ["Coastal Scrub"],
    wildlifeSupportScore: 120,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 10,
    matureHeightFt: 2,
    matureWidthFt: 3,
    growthRate: "Moderate",
    flowerColors: ["white", "pink"],
    bloomMonths: [6, 7, 8],
    indigenousUses: ["seeds ground for food"],
    butterflies: [
      { commonName: "Acmon Blue", scientificName: "Plebejus acmon" },
      { commonName: "Common Ringlet", scientificName: "Coenonympha tullia" },
    ],
    birds: [
      { commonName: "Dark-eyed Junco" },
      { commonName: "White-crowned Sparrow" },
    ],
  },
  {
    scientificName: "Lupinus arboreus",
    commonName: "Yellow Bush Lupine",
    communities: ["Coastal Scrub"],
    wildlifeSupportScore: 140,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 8,
    matureHeightFt: 6,
    matureWidthFt: 8,
    growthRate: "Fast",
    flowerColors: ["yellow", "purple"],
    bloomMonths: [4, 5, 6],
    indigenousUses: ["nitrogen fixation", "seeds ground for food"],
    butterflies: [
      { commonName: "Acmon Blue", scientificName: "Plebejus acmon" },
      { commonName: "Silvery Blue", scientificName: "Glaucopsyche lygdamus" },
    ],
    birds: [
      { commonName: "Dark-eyed Junco" },
      { commonName: "White-crowned Sparrow" },
    ],
  },
  {
    scientificName: "Ceanothus thyrsiflorus",
    commonName: "Blueblossom",
    communities: ["Coastal Scrub", "Chaparral", "Oak Woodland"],
    wildlifeSupportScore: 180,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 25,
    matureHeightFt: 15,
    matureWidthFt: 12,
    growthRate: "Fast",
    flowerColors: ["blue"],
    bloomMonths: [3, 4, 5],
    indigenousUses: ["flowers used as gentle soap"],
    butterflies: [
      { commonName: "Ceanothus Silk Moth", scientificName: "Hyalophora euryalus" },
      { commonName: "Mournful Duskywing", scientificName: "Erynnis tristis" },
    ],
    birds: [
      { commonName: "Wrentit" },
      { commonName: "Anna's Hummingbird" },
    ],
  },
  {
    scientificName: "Fragaria chiloensis",
    commonName: "Coastal Strawberry",
    communities: ["Coastal Scrub"],
    wildlifeSupportScore: 70,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 5,
    matureHeightFt: 0.5,
    matureWidthFt: 2,
    growthRate: "Moderate",
    flowerColors: ["white"],
    bloomMonths: [4, 5, 6],
    indigenousUses: ["berries eaten fresh", "medicinal uses"],
    butterflies: [
      { commonName: "Checkered White", scientificName: "Pontia protodice" },
    ],
    birds: [
      { commonName: "American Robin" },
      { commonName: "Cedar Waxwing" },
    ],
  },
  {
    scientificName: "Achillea millefolium",
    commonName: "Yarrow",
    communities: ["Coastal Scrub", "Grassland", "Oak Woodland"],
    wildlifeSupportScore: 80,
    evergreenDeciduous: "Semi-evergreen",
    lifespanYears: 3,
    matureHeightFt: 2,
    matureWidthFt: 2,
    growthRate: "Fast",
    flowerColors: ["white", "pink"],
    bloomMonths: [5, 6, 7],
    indigenousUses: ["medicinal uses", "wound healing"],
    butterflies: [
      { commonName: "Painted Lady", scientificName: "Vanessa cardui" },
      { commonName: "Common Ringlet", scientificName: "Coenonympha tullia" },
    ],
    birds: [
      { commonName: "Dark-eyed Junco" },
      { commonName: "White-crowned Sparrow" },
    ],
  },
  {
    scientificName: "Festuca rubra",
    commonName: "Red Fescue",
    communities: ["Coastal Scrub"],
    wildlifeSupportScore: 60,
    evergreenDeciduous: "Evergreen",
    lifespanYears: 8,
    matureHeightFt: 2,
    matureWidthFt: 2,
    growthRate: "Moderate",
    flowerColors: ["green"],
    bloomMonths: [5, 6],
    indigenousUses: ["seeds ground for food"],
    butterflies: [
      { commonName: "Common Ringlet", scientificName: "Coenonympha tullia" },
    ],
    birds: [
      { commonName: "Dark-eyed Junco" },
      { commonName: "White-crowned Sparrow" },
    ],
  },
];

export function getPlantsForRegion(region: string): Plant[] {
  return PLANTS.filter(plant => 
    plant.communities.includes(region as PlantCommunity)
  ).slice(0, 10); // Return top 10 plants (reduced from 15)
}
